openapi: 3.0.0

info:
  title: "my first yml flask application"
  description: "first appliction that  i utilised flask and yml"
  version: "1.0.0"

servers: 
  - url: "/api"

components:
  schemas:
    Person:
      type: "object"
      required:
        - lname
      properties:
        fname: 
          type: "string"
        lname:
          type: "string"

paths:
  /people: 
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "read the list of all people"
      responses:
       "200":
         description: "success"
         
    post:
      operationId: "people.create_people"
      tags:
        - "People"
      summary: "create people"
      requestBody:
        description: "person to create"
        required: True
        content:
          application/json: 
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Person"
      responses:
        "201":
          description: "successfully created a person"
